Net:
  enc_type: 'xception65'
  dec_type: 'aspp'
  output_stride: 8

Data:
  dataset: 'cityscapes'
  preprocess: 'deeplab'
  target_size:

Train:
  max_epoch: 20
  batch_size: 2
  resume: True
  start_epoch: 0

Loss:
  weight:
  size_average: True
  batch_average: True

Optimizer:
  mode: 'adam'
  base_lr: 0.001
  t_max: 10
