Net:
  enc_type: 'resnet18'
  dec_type: 'unet_scse'
  num_filters: 8
  pretrained: True

Data:
  dataset: 'pascal'
  preprocess: 'imagenet'
  target_size: (256, 256)

Train:
  max_epoch: 20
  batch_size: 2
  resume: False
  start_epoch: 0

Loss:
  weight:
  size_average: True
  batch_average: True

Optimizer:
  mode: 'adam'
  base_lr: 0.001
  t_max: 10
